#!/bin/bash

read_limit=25
write_limit=10000
astyanax_concurrency=4

while getopts ":a:r:w:" opt; do
  case $opt in
    a)
      astyanax_concurrency=$OPTARG
      ;;
    r)
      read_limit=$OPTARG
      ;;
    w)
      write_limit=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument" >&2
      exit 1
  esac
done

mvn clean test -Dtest=PremigrationTest

rm -rf target/cassandra/node0/data/rhq/*
cp -R /Users/jsanda/tmp/COMPACTED/rhq target/cassandra/node0/data
rm -rf target/cassandra/node0/commit_log/*

./target/cassandra/node0/bin/cassandra -p cassandra.pid

echo "Waiting for creation of cassandra super user..." 
sleep 20

./target/cassandra/node0/bin/cqlsh -u cassandra -p cassandra -f create_rhqadmin.cql

mvn -o test -Dtest=MigrationTest -Drhq.storage.deploy=false -Drhq.storage.shutdown=false -Drhq.storage.request.read-limit=$read_limit -Drhq.storage.request.write-limit=$write_limit 
